### ISSUE TITLE
Add a lock system for megacollabs to prevent ratelimit, of 20 users per round.

### ISSUE THREAD

**Issue by htc480** [XegSo/Miira#6]
Inscription gets blocked for 5 minutes every 20 collab entries on the registering process.

**Comment by Tunnelbliick** [comment]
i think theres to much emphasis on this

> If a rate limit is exceeded (currently, 50 requests per second), the API will return a HTTP 429 response code. The limit for invalid requests is currently 10,000 per 10 minutes

**Comment by htc480** [comment]
I'm afraid because of the times the old bots have crashed due to a lot of users trying to join lol, idk if mongo, discord or osu will die on opening, what do you think would be optimal?

**Comment by htc480** [comment]
I'll also run a stress dummy collab test before public opening where everyone will be able to join and stuff to further look for improvement

**Comment by htc480** [comment]
Added, needs heavy testing
