### ISSUE TITLE
Add a request image change on collabs, if a property of the collab (on the database) itself allows it. 

### ISSUE THREAD

**Issue by htc480** [XegSo/Miira#8]
Interaction shows a modal requiring an URL, and once sent, an embed is sent in a channel where only staff can accept or decline the request, and if accepted, it changes the image URL on the database

**Comment by Tunnelbliick** [comment]
Reminder that each request should be stored as object by itself.

Since if the person requests an image change again there should be 2 different Requests with different Ids and states.

Each one can overwrite the actuall image depending on the order of acceptance.

**Comment by htc480** [comment]
Added
